### ISSUE TITLE
Files with a separator other than "comma" are not parsed correctly.

### ISSUE THREAD

**Issue by detlefvolmer** [arnaudelub/flutter_packages#1]
Files with a separator other than "comma" are not parsed correctly.
I attach some screeenshots with explanations in the pictures. The breakpoint shows where I took the pics.

Not working with semicolon.
![2021-04-04 18_41_15-Window](https://user-images.githubusercontent.com/15838084/113515890-80d4ab00-9577-11eb-8845-928a72a8bf52.png)

Working with comma.
![2021-04-04 18_45_51-Window](https://user-images.githubusercontent.com/15838084/113515915-a497f100-9577-11eb-9e06-dd537d889f81.png)

Working with comma.
![2021-04-04 18_46_44-Window](https://user-images.githubusercontent.com/15838084/113515921-ad88c280-9577-11eb-9977-a032e6a7111e.png)

**Comment by arnaudelub** [comment]
thanks for the screenshots.
Can you please show me the code where csv_parser_button is implemented?

**Comment by detlefvolmer** [comment]
You should have received an invitation to the repo.
Please handle with care, it accessses Firebase live.

The call is in "events_screen.dart" line# 246.

Thank you

**Comment by arnaudelub** [comment]
have you tried updating the separator value of the CsvConfiguration to Separator.semiColumn?

**Comment by detlefvolmer** [comment]
Yes, I've tried semicolon, tab, pipe, etc. 
I created a CSV file with a German Excel. Semicolon is the standard.

**Comment by detlefvolmer** [comment]
I put my data in the repo. Don't want to upload them here.

**Comment by arnaudelub** [comment]
yes indeed, thank you for pointing it out. Fix has just been uploaded to pub.dev.
Let me know if it's working as expected.

**Comment by detlefvolmer** [comment]
Would you mind correctiong the typos for semicolon instead of semi-column and comma instead of come as well? Thank you.

**Comment by arnaudelub** [comment]
sure thing, just done! thanks

**Comment by detlefvolmer** [comment]
Just tested the recent version. Works perfectly with semicolon! Thank you.

**Comment by arnaudelub** [comment]
perfect, thanks for the feedback.
I am closing the issue then!
